server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/students_choose_lodge_database?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 12345678
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapper/*Dao.xml
  typeAliasesPackage: com.example.shopping.entity